[tool.poetry]
name = "onlinelessons"
version = "0.1.0"
description = ""
authors = ["jylu lyapunova <jylilapa@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1.6"
black = "^25.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
